name: COBOL Check Automation

on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10   # Automatically stop job if it exceeds 10 minutes

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Java (required by COBOL Check)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3️⃣ Setup Node.js (for Zowe CLI)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 4️⃣ Install Zowe CLI
      - name: Install Zowe CLI
        run: npm install -g @zowe/cli --prefer-offline

      # 5️⃣ Configure Zowe CLI profile (using GitHub Secrets)
      - name: Configure Zowe CLI profile
        env:
          ZOS_HOST: ${{ secrets.ZOS_HOST }}
          ZOS_PORT: ${{ secrets.ZOS_PORT }}
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: |
          echo "🔧 Configuring Zowe CLI profile..."
          zowe config init
          zowe config set profiles.zosmf.type zosmf
          zowe config set profiles.zosmf.properties.host "$ZOS_HOST"
          zowe config set profiles.zosmf.properties.port "$ZOS_PORT"
          zowe config set profiles.zosmf.properties.user "$ZOWE_USERNAME"
          zowe config set profiles.zosmf.properties.password "$ZOWE_PASSWORD"
          zowe config set profiles.zosmf.properties.rejectUnauthorized false
          echo "✅ Zowe CLI profile configured successfully."

      # 6️⃣ Verify Zowe CLI installation
      - name: Check Zowe CLI version
        run: |
          echo "📦 Zowe CLI version:"
          zowe --version

      # 7️⃣ Upload COBOL Check files to Mainframe USS
      - name: Setup MainFrame Environment and Upload COBOL Check
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: |
          echo "📤 Uploading COBOL Check files to Mainframe USS..."
          chmod +x .github/scripts/zowe_operations.sh
          .github/scripts/zowe_operations.sh
          echo "✅ Upload complete."

      # 8️⃣ Run COBOL Check on Mainframe
      - name: Run COBOL Check on Mainframe
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: |
          echo "🧩 Running COBOL Check on z/OS..."
          chmod +x .github/scripts/mainframe_operations.sh
          .github/scripts/mainframe_operations.sh
          echo "✅ COBOL Check execution completed successfully."
