name: COBOL Check Automation

on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 소스 코드 체크아웃
    - uses: actions/checkout@v2

    # 2. Java 11 설정 (오류 수정: distribution 추가)
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin' 
        
    # 3. COBOL Check 실행 환경 설정 및 실행
    - name: Setup MAinFrame Enviornment and Upload COBOL Check
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
      run: |
        chmod + x . github / scripts / zowe_operations.sh
        .github / scripts / zowe_operations . sh
