name: COBOL Check Automation

on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10   # stop job automatically after 10 mins

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Java (needed for cobol-check)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3️⃣ Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 4️⃣ Install Zowe CLI
      - name: Install Zowe CLI
        run: npm install -g @zowe/cli --prefer-offline

      # 5️⃣ Configure Zowe CLI profile (with safe defaults)
      - name: Configure Zowe CLI profile
        run: |
          zowe config init
          zowe config set profiles.zosmf.type zosmf
          zowe config set profiles.zosmf.properties.host "${{ secrets.ZOS_HOST || 'dummy-host' }}"
          zowe config set profiles.zosmf.properties.port "${{ secrets.ZOS_PORT || '443' }}"
          zowe config set profiles.zosmf.properties.user "${{ secrets.ZOWE_USERNAME || 'dummy-user' }}"
          zowe config set profiles.zosmf.properties.password "${{ secrets.ZOWE_PASSWORD || 'dummy-pass' }}"
          zowe config set profiles.zosmf.properties.rejectUnauthorized false

      # 6️⃣ Check Zowe CLI version (optional sanity check)
      - name: Check Zowe CLI version
        run: zowe --version

      # 7️⃣ Upload COBOL Check files to Mainframe (USS upload)
      - name: Setup MainFrame Environment and Upload COBOL Check
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: |
          echo "📤 Uploading COBOL Check files to Mainframe..."
          chmod +x .github/scripts/zowe_operations.sh
          .github/scripts/zowe_operations.sh
          echo "✅ Upload complete."

      # 8️⃣ Run COBOL Check on Mainframe
      - name: Run COBOL Check on Mainframe
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: |
          echo "🧩 Running COBOL Check on z/OS..."
          chmod +x .github/scripts/mainframe_operations.sh
          .github/scripts/mainframe_operations.sh
          echo "✅ COBOL Check execution finished."
