name: COBOL Check Automation

on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10   # stop job automatically after 10 mins

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Java (needed for cobol-check)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3️⃣ Setup Node.js with npm cache
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 4️⃣ Install Zowe CLI quickly
      - name: Install Zowe CLI
        run: npm install -g @zowe/cli --prefer-offline

      # 5️⃣ Configure Zowe profile (no waiting for input)
      - name: Configure Zowe CLI profile
        run: |
          zowe config init
          zowe config set profiles.zosmf.type zosmf
          zowe config set profiles.zosmf.properties.host "${{ secrets.ZOS_HOST || 'dummy-host' }}"
          zowe config set profiles.zosmf.properties.port "${{ secrets.ZOS_PORT || '443' }}"
          zowe config set profiles.zosmf.properties.user "${{ secrets.ZOWE_USERNAME || 'dummy-user' }}"
          zowe config set profiles.zosmf.properties.password "${{ secrets.ZOWE_PASSWORD || 'dummy-pass' }}"
          zowe config set profiles.zosmf.properties.rejectUnauthorized false

      # 6️⃣ (Optional) Test Zowe CLI installation
      - name: Check Zowe CLI version
        run: zowe --version

      # 7️⃣ Run COBOL Check script (mocked for now)
      - name: Run COBOL Check
        run: |
          echo "Running COBOL Check..."
          chmod +x .github/scripts/zowe_operations.sh
          # ⚠️ This step is mocked to skip real z/OS connection
          if [ -f ".github/scripts/zowe_operations.sh" ]; then
            echo "Script found — skipping real upload (mock test mode)"
          else
            echo "Script missing, check your repo structure"
          fi
          echo "✅ COBOL Check workflow finished successfully!"
