name: COBOL Check Automation

on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v2

      # 2. Set up Java
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Set up Node.js (required for npm)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 4. Install Zowe CLI
      - name: Install Zowe CLI
        run: npm install -g @zowe/cli

      # 5. Configure Zowe profile (so commands can connect)
      - name: Configure Zowe CLI profile
        run: |
          zowe config init
          zowe config set profiles.zosmf.type zosmf
          zowe config set profiles.zosmf.properties.host ${{ secrets.ZOS_HOST }}
          zowe config set profiles.zosmf.properties.port ${{ secrets.ZOS_PORT }}
          zowe config set profiles.zosmf.properties.user ${{ secrets.ZOWE_USERNAME }}
          zowe config set profiles.zosmf.properties.password ${{ secrets.ZOWE_PASSWORD }}
          zowe config set profiles.zosmf.properties.rejectUnauthorized false


      # 6. Run your COBOL Check script
      - name: Run COBOL Check Script
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: |
          chmod +x .github/scripts/zowe_operations.sh
          .github/scripts/zowe_operations.sh
